### ISSUE TITLE
fish movement ambiguity

### ISSUE THREAD

**Issue by mhrimaz** [se2p/programming-styles-ss-2020-program-description#12]
You have mentioned in the description that:

> Note that, to ensure predictability, the fish/prey that must be moved in this case is the one closest to safety. In case of a tie, the fish/prey which corresponds to the smallest number among the ones that are closest to safety can move.

So the closest fish to the sea will move and in case of a tie, the one with smallest id will move. But in the example you wrote somehow different.

> As a result, the fish with the smallest id (which is coincidentally the closest to the sea in this case) should move. This is fish 3.

According to this description, I can conclude that always the fish with smallest id will move in such cases. 
This case is obvious, the fish 3 will move (input is 2).

```
╔════════╤═══╤═══╤═══════╗
║  ┌──┐1 │   │   │   2   ║
║  │  │  │ 3 │   │       ║
║  │4 │  │   │   │       ║
║  └──┘6 │ 5 │   │       ║
╚════════╧═══╧═══╧═══════╝
```

But how about this case (input is 2)? I think the fish number 5 should move, because it is the closest fish.
```
╔════════╤═══╤═══╤═══════╗
║  ┌──┐1 │   │   │   2   ║
║  │  │  │ 3 │   │       ║
║  │4 │  │   │   │       ║
║  └──┘6 │   │ 5 │       ║
╚════════╧═══╧═══╧═══════╝
```

**Comment by alessiogambi** [comment]
Good catch. The specifications say to move the closest one and, only in case of a tie, to move the fish with the smallest id. So in the cases above, in the first one fish 3 moves, which in the second case 5 moves. Let me fix this
