### ISSUE TITLE
imbalance alignment clarification

### ISSUE THREAD

**Issue by mhrimaz** [se2p/programming-styles-ss-2020-program-description#14]
What should we do in case that the alignment is not possible perfectly? I believe we should have more spaces on the left hand side. Can you confirm it?

This one is not correct
```
 ╔════════╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══════╗  
┌───────────────────────────────────────────────┐
│ XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX │
│                   XXXXXXXXXX                  │
└───────────────────────────────────────────────┘
 ╚════════╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══════╝ 
```
This one is correct
```
  ╔════════╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══════╗ 
┌───────────────────────────────────────────────┐
│ XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX │
│                   XXXXXXXXXX                  │
└───────────────────────────────────────────────┘
  ╚════════╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══════╝ 
```

**Comment by alessiogambi** [comment]
Hi, this is mentioned in the README:
> The banner containing the message must span over the entire board and go over it by one unit per side (see below). The message must be centered inside its banner. In case the message cannot be perfectly centered, add one empty space on the left side of the message.

It should be possible to always increase the size of the banner such that it is centered. The message inside the banner instead might be one space off if a perfect alignment is not possible.

So in your example the current answer should be:

```
  ╔════════╤═══╤═══╤═══╤═══╤═══╤═══╤═══╤═══════╗ 
┌────────────────────────────────────────────────┐
│  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX │
│                   XXXXXXXXXX                   │
└────────────────────────────────────────────────┘
  ╚════════╧═══╧═══╧═══╧═══╧═══╧═══╧═══╧═══════╝ 
```
